### ISSUE TITLE
Attributes field is missing

### ISSUE THREAD

**Issue by barimale** [lvermeulen/Keycloak.Net#10]
Please extend Keycloak.Net.Models.Roles.Role class as follows:

[JsonProperty("attributes")]
public Dictionary<string, string> Attributes { get; set; }

**Comment by lvermeulen** [comment]
Done. Can you submit a PR next time? Makes it easier for me.

**Comment by barimale** [comment]
Sure, thanks Luk Sent from Mail for Windows 10 From: Luk VermeulenSent: Thursday, March 5, 2020 5:52 PMTo: lvermeulen/Keycloak.NetCc: barimale; AuthorSubject: Re: [lvermeulen/Keycloak.Net] Attributes field is missing (#10) Done. Can you submit a PR next time? Makes it easier for me.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avg.com
