### ISSUE TITLE
Find an alternative to JsonConvert.DefaultSettings

### ISSUE THREAD

**Issue by nebenjamin** [lvermeulen/Keycloak.Net#11]
In the static constructor for KeycloakClient, a method is assigned to JsonConvert.DefaultSettings that sets the contract resolver to CamelCasePropertyNamesContractResolver. When using this library in a project that is already using Json.Net (Newtonsoft.Json), this will overwrite the default settings across the entire project.

As an example, I have a project that frequently serializes to/deserializes from JSON. Until an instance of KeycloakClient is created Json.Net's default TitleCasing is used, and after the instantiation occurs all of the objects that I've previously serialized can no longer be deserialized.

What makes this worse is that the serialization/deserialization happens in 2 separate services, one that has a reference to Keycloak.Net and one that doesn't. The end result is that while the service that uses Keycloak.Net would be able to deserialize the object correctly, the one that doesn't is still expecting the serialized object to be TitleCased.

I'm definitely planning on putting in the time to work on this and create a PR, but I'm curious about the original motivations to put this in place so I'm not causing a regression.

**Comment by lvermeulen** [comment]
Hi Nathan,

The original motivation was: apply CamelCase. :-) If you find a better way, I'll be interested to look at your PR!

Regards,

Luk

**Comment by lvermeulen** [comment]
Fixed in release [1.0.11](https://github.com/lvermeulen/Keycloak.Net/releases/tag/1.0.11)
