### ISSUE TITLE
GetUserForServiceAccountAsync Obsolete?

### ISSUE THREAD

**Issue by agentschmitt** [lvermeulen/Keycloak.Net#17]
Hi you marked GetUserForServiceAccountAsync as oboslete not working.
But for me your function is working with Keycloak Server 6.0.1.
Of course only for clients with ServiceAccountsEnabled, otherwise the api returns 404 which leads to crash in your function.
Is this the reason why it is marked not working or is this deprecated in future keycloak versions?

**Comment by lvermeulen** [comment]
I marked some methods as obsolete because my test was failing. Glad to hear it's working!
