### ISSUE TITLE
How to create a new user with client roles

### ISSUE THREAD

**Issue by jScope** [lvermeulen/Keycloak.Net#18]
Hello,

I have a basic question and I hope you can help me. Probably it's very stupid.

I'm able to create new users without problems but now I would like to pass client roles with the new user on create. I have to pass a dictionary<string, object> but how does the dictionary really have to look like if I want to pass multiple client-roles for multiple clients?

At the moment I pass it like this but the role is not assigned to the new user afterwards.
`ClientRoles = 
                    new Dictionary<string, object>() { { "client_name", new string[] { "client_role_name" } }`

Can you please give a simple example.

Thank you very much!

**Comment by lvermeulen** [comment]
Hi @jScope , to be perfectly honest I have no idea. I was using Keycloak in a previous project, but I'm not anymore. Maybe someone who's reading this can help you out?

**Comment by jScope** [comment]
Hello @lvermeulen,

thank you for your quick reply. From my current investigations it looks like that Keycloak Admin REST Api really wants each resource update in seperate request. So I have to create the user as I do already and then add roles to the created user. I found the desired method _AddClientRoleMappingsToUserAsync_ for that task in your library under ClientRoleMappings folder.

So you don't plan to update this package with ongoing Keycloak releases? I just ask because you did a release of this package recently and it's very helpful.

At the moment there doesn't seem to be any better mentained alternatives for .Net.

**Comment by lvermeulen** [comment]
Hi @jScope , I did a little bit of investigating into this issue. Here's what I found:

* This is an unfinished PR for the functionality that you requested: https://github.com/keycloak/keycloak/pull/3120
* This issue says it's not possible right now: https://issues.redhat.com/browse/KEYCLOAK-12460

When this is ever added to the API, and you give me a signal, I am perfectly willing to add this in.
