### ISSUE TITLE
Role Attributes Type

### ISSUE THREAD

**Issue by WereWOLFius** [lvermeulen/Keycloak.Net#22]
Hi.

I use keycloak server 10.0.2 and using this library ran into a problem:
Server returns role attributes differently than specified in the class model.

If change role Attributes field from:
IDictionary<string, string>
to:
Dictionary<string, IEnumerable<string>>
Deserialization is successful.

I would be grateful if you update the library and I don't have to use a local modified copy.

With best regards

**Comment by lvermeulen** [comment]
Hi @WereWOLFius , which call are you referring to?
