### ISSUE TITLE
add support for Protection API?

### ISSUE THREAD

**Issue by timiil** [lvermeulen/Keycloak.Net#3]
as the title, do we have any plan to support Protection API ?

for example from 
Creating a Resource
To create a resource you must send an HTTP POST request as follows:

```
curl -v -X POST \
  http://${host}:${port}/auth/realms/${realm_name}/authz/protection/resource_set \
  -H 'Authorization: Bearer '$pat \
  -H 'Content-Type: application/json' \
  -d '{
     "name":"Tweedl Social Service",
     "type":"http://www.example.com/rsrcs/socialstream/140-compatible",
     "icon_uri":"http://www.example.com/icons/sharesocial.png",
     "resource_scopes":[
         "read-public",
         "post-updates",
         "read-private",
         "http://www.example.com/scopes/all"
      ]
  }'

```

**Comment by lvermeulen** [comment]
Not at this moment, I'm afraid. Maybe I'll get to it some day, but I also accept PR's. :-)

**Comment by lvermeulen** [comment]
So I decided to implement this. You can find the project at [Keycloak.Protection.Net](https://github.com/lvermeulen/Keycloak.Protection.Net). A pre-release version is available on NuGet.

**Comment by timiil** [comment]
very nice!
