### ISSUE TITLE
Security Warning

### ISSUE THREAD

**Issue by mnoseworthy** [lvermeulen/Keycloak.Net#39]
I'm not sure that this actually matters to anyone, but when building a license file for a distribution I generally copy-paste the Package name into my browser. In the case of this Package, it sends you to a domain not controlled by Redhat.

Sorry if this is just bloat, but wanted to at least alert the potential security concern.

```
     Name: KEYCLOAK.NET
    Registry Domain ID: 2134538313_DOMAIN_NET-VRSN
    Domain Status:

    clientDeleteProhibited

    clientTransferProhibited

    clientUpdateProhibited
    Nameservers:

    NS73.DOMAINCONTROL.COM

    NS74.DOMAINCONTROL.COM

Dates

    Registry Expiration: 2021-06-17 05:34:44 UTC
    Created: 2017-06-17 05:34:44 UTC
```

**Comment by lvermeulen** [comment]
Thanks @mnoseworthy
