### ISSUE TITLE
Non-Existant Documentation

### ISSUE THREAD

**Issue by patrickmilnes** [lvermeulen/Keycloak.Net#45]
Hi,

Does actual docuementation of the package exist?

The current link to the docs is not documentation for this package, but for something else.

I might be missing something, but I can figure out how to use this package by just the keycloak rest api docs.

Thanks,
Pat

**Comment by lvermeulen** [comment]
There is no documentation of this package beyond the README.md. Since this was something I worked on during my sparse free time, I chose to devote my time to implementing features instead of writing documentation. I welcome a pull request to add documentation, though.
