### ISSUE TITLE
Flurl.StringExtensions

### ISSUE THREAD

**Issue by Andrej997** [lvermeulen/Keycloak.Net#48]
Hello,

I'm getting this error, what doe's it mean?
System.TypeLoadException: Could not load type 'Flurl.StringExtensions' from assembly 'Flurl, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null'

Thank you in advance!

Kind Regards,
Andrej

**Comment by lvermeulen** [comment]
I'm using Flurl.Http 2.4.2 which uses Flurl 2.8.2 under the hood. It seems like you are using a different version in your project.
