### ISSUE TITLE
documentation, says it works with keycloak 6, recently installed keycloak and it is version 13.0.0

### ISSUE THREAD

**Issue by karezza** [lvermeulen/Keycloak.Net#56]
Request to update the version this works with.

I see the plugin was recently updated May 7, 2021 so I presume it works but was discouraged when I saw version 6 in the documentation.

Also, the documentation links over to keycloak rest api, but an example with c# would be more helpful.  Such as an example which shows what should be in the Startup.cs to get things working on the server side & something similar on the client side.

**Comment by karezza** [comment]
found an alternative solution

**Comment by takato1314** [comment]
@karezza may I know what's the alternative solution you've used for versions higher than 13.0?
