### ISSUE TITLE
Documation for Keycloak.Net

### ISSUE THREAD

**Issue by thanhtai9606** [lvermeulen/Keycloak.Net#78]
I can not find any documentation to use this library. How can find it??

**Comment by psavva** [comment]
Have a look at the examples in https://github.com/lvermeulen/Keycloak.Net/tree/main/test/Keycloak.Net.Tests

**Comment by joelvega** [comment]
This doesn't answer the very valid question of "where is the documentation"? I cannot find a single shred of documentation for Keycloak.Net. Is a user simply supposed to know what was in the developer's brains when they developed the code?

I am trying to create a realm, nowhere on the internet shows you how to do that. I can search through the hundreds of functions manually and find ImportRealmAsync, but the developer cannot even leave a comment in the code to tell you what the parameters even represents. The first parameter is a string named realm. Is this the name of the realm that you want to create? No idea, you just have to read the developer's mind.
